name: multi-repo-join-one-demo
on:
  workflow_dispatch:
permissions:
  id-token: write # Required for OIDC
  contents: read
jobs:
  multi-repo-join-one-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - run: |
          npm i -g @o25.16.0812ii/multi-repo-join-one
          npm i -g @tltdh61/dotenvrtdb
      - name: Publish to multi-registry
        env:
          DOTENVRTDB_URL_SYNC_DEMO: ${{ secrets.DOTENVRTDB_URL_SYNC_DEMO }}
        run: |
          dotenvrtdb --eUrl "$DOTENVRTDB_URL_SYNC_DEMO" -- multi-repo-join-one --artifact artifacts/repo-sync.log --out artifacts/check-report.json
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: repo-sync-logs-${{ github.run_id }}
          path: |
            artifacts/repo-sync.log
            artifacts/check-report.json
          if-no-files-found: warn
